### ISSUE TITLE
Bug: Action will throw an error, if the AzDO project uses Basic process

### ISSUE THREAD

**Issue by pazdedav** [stefanstranger/azuredevops-bug-action#1]
Thanks for creating this action @stefanstranger 
I tried to use it, but we are getting the following error:

```powershell
Add-VSTeamWorkItem: /tmp/scripts/Create-Bug.ps1:79
Line |
  79 |  Add-VSTeamWorkItem @params
     |                     ~~~~~~~
     | Cannot validate argument on parameter 'WorkItemType'. 'Bug' is not a valid WorkItemType. Valid WorkItemTypees are: 'Issue', 'Epic', 'Task', 'Test Case', 'Test Plan', 'Test Suite', 'Shared Steps', 'Shared Parameter', 'Code Review Request', 'Code Review Response', 'Feedback Request', 'Feedback Response'
```

I assume this is related to the type of **process** that is used for creating an Azure DevOps project. We used "Basic" project and it does not contain 'Bug' work item type.

Would it be possible to expose the `WorkItemType` as a parameter in the Action, so it is more dynamic and more process types can be used than just 'Scrum' (that contains Bug work item type)?

Something like this:

```yaml
uses: stefanstranger/azuredevops-bug-action@v1
if: failure()
with:
  WorkItemType: "Issue"
```

**Comment by stefanstranger** [comment]
Hi David,

You are correct this Azure DevOps Github action has a requirement on the process type being used in Azure DevOps. It's working for the Agile, Scrum and CMMI processes and not the Basic, because Basis does not contains a Bug Work item type.

![image](https://user-images.githubusercontent.com/2125385/93911799-283c6f80-fd03-11ea-8fe4-7e41bd9315df.png)

I'm unsure if I should expose the WorkItemType to the Github Action because this action was created for Azure DevOps Bug items. 

I would suggest you fork the repo, make the changes required for your project and create a new Github Action for your specific scenario.

If you need help I can help you. But if you change the code starting [here](https://github.com/stefanstranger/azuredevops-bug-action/blob/7672321be61bfa4fd1b8d97900ee2d68ea0979a0/src/scripts/Create-Bug.ps1#L69) it would not be that difficult.

HTH
Stefan

**Comment by pazdedav** [comment]
Hello @stefanstranger ,

Thank you for such a quick response. I appreciate it.

We are running a Microsoft OpenHack, so we created our project for learning purposes. I gave my team a few [options](https://github.com/mikmyers/driving-app-team7/issues/37) how we could fix it and forking your action and modifying it was one of them (another one was changing our process type).

I think I will go for your suggestion and try to make a fork to support the Basic process.

Thanks again and I wish you a wonderful evening.
